defaults:
  - search: pure_gad
  - starting: noised_ts
  - calculator: hip
  - logging: default
  - cluster: narval
  - _self_

seed: 42
max_samples: 300
# Available splits: train (9561), test (287), val (225)
# We didn't train on T1x so train split is fair game for evaluation.
split: train
output_dir: /lustre07/scratch/memoozd/gadplus/runs/${now:%Y%m%d_%H%M%S}
